# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [prod-deploy-test]
  pull_request:
    branches: [prod-deploy-test]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: NODE_ENV=production npm run strapi build

      - name: Start project
        env:
          DOMAIN: "167.172.248.211"

          CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET_DEV}}
          CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME_DEV}}
          CLOUDINARY_KEY: ${{secrets.CLOUDINARY_KEY_DEV}}

          DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}

          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY_PROD}}
        run: pm2 start ecosystem.config.js
      - run: pm2 reload back
